services:
- name: docker:dind
stages:
- build
- release
variables:
  CONTAINER_TEST_IMAGE: registry.nodestack.xyz/scalefog/apidoc:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.nodestack.xyz/scalefog/apidoc:latest
before_script:
  - docker login -u kenneth -p Noksu852 registry.nodestack.xyz
build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  tags:
  - docker
release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
  tags:
  - docker
